// <auto-generated />
using Contratos.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contratos.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210225022409_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contratos.WebAPI.Model.DocumentoContratualModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataFimVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataInicioVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkRedmine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetoAcordo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessoTCE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentosContratuais");
                });
#pragma warning restore 612, 618
        }
    }
}
